### ISSUE TITLE
[BUG] Fails to detect game directory or extract any files on Linux

### ISSUE THREAD

**Issue by lat9nq** [xypwn/filediver#5]
**System info:**
- Filediver version: 77f1aa8
- OS: 
```
System:
  Host: qykopi Kernel: 6.7.10-200.fc39.x86_64 arch: x86_64 bits: 64
    compiler: gcc v: 2.40-14.fc39
  Desktop: GNOME v: 45.5 tk: GTK v: 3.24.41 wm: gnome-shell dm: GDM
    Distro: Fedora Linux 39 (Workstation Edition)
```

**Describe the bug**
Fails to extract any files.

**To Reproduce**
- Run: `filediver -g ~/.local/share/Steam/steamapps/common/Helldivers\ 2/ -c "audio:format=source" -i 'content/audio/*.wise_stream'`

**Expected behavior**
I expect there to be any output.

**Command line output**
```
INFO Game directory: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
INFO Output directory: "extracted"
INFO Reading metadata...
INFO Extracting files...
INFO Extracted 0/0 matching files
```

**Additional context**
https://github.com/Xaymar/Hellextractor/pull/30#issuecomment-2030357154

I first tried extracting the Helldivers 2 data to a completely unrelated directory and specifying -g to the game, and the path to the content relative to my working directory. I then tried leaving the data in the Helldivers 2 directories and specifying the path relative to the game path. Doesn't seem to pick up on any files and I cannot tell where it is looking.

**Comment by xypwn** [comment]
It should try to look for the game files in the "Helldivers 2/data" directory. Could you please post the output of `ls /home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2/data`

**Comment by lat9nq** [comment]
[data.txt](https://github.com/xypwn/filediver/files/14828846/data.txt)
This might be a slightly old version of the game as I haven't started Steam in a few days.

**Comment by xypwn** [comment]
I just updated the code to include the "Steam" portion of the steam path. Can you see if it detects your game directory correctly now?

**Comment by xypwn** [comment]
lol I found why it didn't find any files. You wrote "wise_stream" instead of "wwise_stream".

**Comment by lat9nq** [comment]
> lol I found why it didn't find any files. You wrote "wise_stream" instead of "wwise_stream". It should work if you change it wwise_stream :)

Apologies, the provided example is indeed incorrect. I have also tried copy-pasting the file name to no effect.

**Comment by lat9nq** [comment]
> I just updated the code to include the "Steam" portion of the steam path. Can you see if it detects your game directory correctly now?

It detects the game directory automatically now.
```
$ filediver -c "audio:format=source" -i 747204275.wwise_stream
INFO Using game found at: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
INFO Output directory: "extracted"
INFO Reading metadata...
INFO Extracting files...
INFO Extracted 0/0 matching files
```

**Comment by lat9nq** [comment]
Oh and also, sorry I haven't been of much help with providing patches to the source: Go is completely foreign to me.

**Comment by xypwn** [comment]
> Oh and also, sorry I haven't been of much help with providing patches to the source: Go is completely foreign to me.

No need to apologize :)

**Comment by xypwn** [comment]
> > I just updated the code to include the "Steam" portion of the steam path. Can you see if it detects your game directory correctly now?
> 
> It detects the game directory automatically now.
> 
> ```
> $ filediver -c "audio:format=source" -i 747204275.wwise_stream
> INFO Using game found at: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
> INFO Output directory: "extracted"
> INFO Reading metadata...
> INFO Extracting files...
> INFO Extracted 0/0 matching files
> ```

You need to specify the full path. If you want to match the file in any path, you need to use `filediver -c "audio:format=source" -i "**747204275.wwise_stream"`

**Comment by lat9nq** [comment]
> You need to specify the full path. If you want to match the file in any path, you need to use `filediver -c "audio:format=source" -i "**747204275.wwise_stream"`

Does the extracted data need to be in a specific location for this to work? Or is it extracting from the game files directly?

The suggestion did not solve the issue.

**Comment by xypwn** [comment]
It doesn't matter where you extract it to. The program should automatically detect where the game is installed and extract it to the "extracted" folder in your current folder.

Maybe I misremembered the specific glob library's syntax. Can you try `filediver -c "audio:format=source" -i "**/747204275.wwise_stream"`.
Did the full path not work btw?

**Comment by lat9nq** [comment]
I'm not seeing any combination of relative, absolute, or glob directories that work here.

`filediver -c "audio:format=source" -i "*/747204275.wwise_stream"`
`filediver -c "audio:format=source" -i "**/747204275.wwise_stream"`
`filediver -c "audio:format=source" -i $(readlink -e 747204275.wwise_stream)` -- expands to `filediver -c "audio:format=source" -i /home/lat9nq/Games/hd2/content/audio/747204275.wwise_stream`

**Comment by xypwn** [comment]
Ohh, I misunderstood what you were trying to do.
I thought you wanted to extract the audio from the game files. Filediver doesn't support converting files that are already ripped from the game. It rips the files itself, optionally converting them. Converting files is what vgmstream etc. are for.

**Comment by xypwn** [comment]
I also fixed a bug related to glob evaluation recently. Can you try the previous command again after a git pull and rebuild?

**Comment by lat9nq** [comment]
I'm not seeing any change, unfortunately.

**Comment by xypwn** [comment]
I see now. It's because the path to your file is not present in my hash list.
If you can give me a link to the hash list you got the file path from, I'd be happy to add it to my hash list.

**Comment by lat9nq** [comment]
If that's the case, `**/**.wwise_stream` would work, wouldn't it?

FWIW whichever of the appropriate .txt files on the root directory of https://github.com/Xaymar/Hellextractor would be where it came from.

**Comment by xypwn** [comment]
I did also take the strings from hellextractor, but apparently I haven't kept them entirely up to date, so I'll add them.
While selecting all wwise_stream files will also extract the file you're after, filediver won't know the name of the file since all that is present in the actual game files is the name's hash.

**Comment by lat9nq** [comment]
For sake of clarity I only randomly picked that file out of the Hellextractor output. I don't know what any of these are, and I don't really have any way of telling what any of it is or if it's even valid data.

**Comment by xypwn** [comment]
Alright, I merged the new hellextractor hashes. It should have the name you mentioned among others that were missing now. Thanks for pointing that out.

**Comment by lat9nq** [comment]
Okay, my issue seems that the hashes file needs to be specified if I'm running filediver from a different location. Once I specified `--hashes_file` I got usable output.

This seems like an opportunity for the program to error out if there are no hashes, since I'm not sure what it can do without them. If this was a CMake/C++ project I'd offer to help integrating the hashes into the executable, so it's just there all the time but optionally a user could specify their own hashes file.

**Comment by xypwn** [comment]
It already embeds the hashes.txt file in the current directory when filediver is built.

**Comment by xypwn** [comment]
Maybe you forgot to git pull and/or rebuild

**Comment by lat9nq** [comment]
Unless `go build` isn't the command to rebuild it, I'm fairly certain I've been rebuilding the executable before I used it.

**Comment by xypwn** [comment]
It works for me. Again, make sure you're using the newest version

**Comment by lat9nq** [comment]
```
[lat9nq@qykopi ~]$ filediver -c "audio:format=source" -i "content/audio/**"
INFO Using game found at: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
INFO Output directory: "extracted"
INFO Reading metadata...
INFO Extracting files...
INFO Extracted 6/6 matching files
[lat9nq@qykopi ~]$ filediver --hashes_file /home/lat9nq/repos/filediver/hashes.txt -c "audio:format=source" -i "content/audio/**"
INFO Using game found at: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
INFO Output directory: "extracted"
INFO Reading metadata...
INFO Extracting files...
INFO Extracted 10492/10492 matching files
```

**Comment by lat9nq** [comment]
```
[lat9nq@qykopi ~]$ cd repos/filediver/
[lat9nq@qykopi filediver]$ go build
[lat9nq@qykopi filediver]$ cd
[lat9nq@qykopi ~]$ filediver -c "audio:format=source" -i "content/audio/**"
INFO Using game found at: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
INFO Output directory: "extracted"
INFO Reading metadata...
INFO Extracting files...
INFO Extracted 6/6 matching files
[lat9nq@qykopi ~]$ filediver --hashes_file /home/lat9nq/repos/filediver/hashes.txt -c "audio:format=source" -i "content/audio/**"
INFO Using game found at: "/home/lat9nq/.local/share/Steam/steamapps/common/Helldivers 2"
INFO Output directory: "extracted"
INFO Reading metadata...
INFO Extracting files...
INFO Extracted 10492/10492 matching files
```

**Comment by lat9nq** [comment]
Oh I see what I did, wasn't copying to PATH
Yeah it works now
